### ISSUE TITLE
Adding an optional instance name to --i option

### ISSUE THREAD

**Issue by kiteloopdesign** [cclienti/svmodule#9]
Not sure you have the BW to work on this or open to suggestions? If that is not the case, then please ignore this as it is more a suggestion than an issue

Looks like at the moment the instances of module *my_module* are declared as *my_module_inst* by default. It would be great if the user could change this default naming? For instance I usually name them as *u_my_module*. Sometimes you might have several of them, so you might want to add a suffix, eg. *u_my_module_1*.

Maybe would be possible to add an extra arg to the instance switch `-i`? Something like `-i [instance_name]` ?

**Comment by cclienti** [comment]
Yes it is possible.
